routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('login');
})->name('login');
Route::get('/registrar', function () {
    return view('register');
})->name('registrar.public');

Route::post('auth', 'LoginController@login')->name('auth');
Route::get('/logout', 'LoginController@logout')->name('logout');
Route::resource('/user', 'UserController');

Route::group(['middleware' => 'auth'], function () {
    //middleware auth
    Route::get('/dashboard', 'LoginController@index')->name('dashboard');
});

app/Aperturacomedor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Aperturacomedor extends Model
{
    //
}

app/Rol.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Rol extends Model
{
    protected $table = "roles";

    protected $fillable = ['nombre',];


    }

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
       use Notifiable;

    protected $table = "users";

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nombre', 'email', 'password', 'rol_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}
 
             

app/Http/Controllers/AperturcomedorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class AperturcomedorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/LoginController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class LoginController extends Controller
{
    public function index()
    {
        return view('dashboard', ['users' => User::all()]);
    }

    public function login(Request $request)
    {
        /*----------- LOGIN MANUAL , MODIFICABLE ----------*/
        $this->validate($request, [
            'email'    => 'required|email',
            'password' => 'required',
        ]);

        if (Auth::attempt($request->only(['email', 'password']))) {
            return redirect()->intended('dashboard');
        } else {
            return redirect()->route('login')->withErrors('¡Error! , Revise sus credenciales');
        }
    }

    public function logout()
    {
        /*---- funcion de salir/logout/cerrar sesion --*/
        Auth::logout();
        return redirect('/');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;
use App\Rol;
use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $users = User::all();
        return view('User.index', ['users'=>$users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {    
        $roles = Rol::all();
        return view('User.create',['roles' => $roles]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, [
            'nombre'   => 'required',
            'email'    => 'required|email|unique:users',
            'password' => 'required|min:7|confirmed',
        ]);

        $user = new User;
        $user->fill($request->all());
        $user->password = bcrypt($request->input('password'));

        if ($user->save()) {
            return redirect("/user")->with([
                'flash_message' => 'Usuario agregado correctamente.',
                'flash_class'   => 'alert-success',
            ]);
        } else {
            return redirect("/")->with([
                'flash_message'   => 'Ha ocurrido un error.',
                'flash_class'     => 'alert-danger',
                'flash_important' => true,
            ]);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         $user = User::findOrfail($id);

        return view('user.edit',['user' => $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $user = User::findOrfail($id);

        $this->validate($request, [
            'email' => 'required|email|unique:users,email,' . $user->id . ',id',
        ]);

         $user->fill($request->all());

         if ($user->save()) {
            return redirect("user")->with([
                'flash_message' => 'Usuario modificado correctamente.',
                'flash_class'   => 'alert-success',
            ]);
        } else {
            return redirect("user")->with([
                'flash_message'   => 'Ha ocurrido un error.',
                'flash_class'     => 'alert-danger',
                'flash_important' => true,
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/User/create.blade.php
@extends('layouts.app')

@section('content')

<div class="col-md-8 offset-2">
  <div class="card">
    <div class="card-header">
      <h4 class="card-title" id="basic-layout-form">Nuevo Usuario</h4>
      <p class="mb-0">Registrar usuario nuevo</p>
    </div>
    <div class="card-content">
      <div class="px-3">
        <form class="form" action="{{route('user.store')}}" method="POST">
          @csrf
          <div class="form-body">
            <h4 class="form-section"><i class="ft-user"></i>Información Personal</h4>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group" >
                  <label for="projectinput1">Nombre</label>
                  <input type="text" id="projectinput1" class="form-control" name="nombre">
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group {{ $errors->has('email')? 'error':'' }}">
                  <label for="projectinput3">Correo</label>
                  <input type="text" id="projectinput3" class="form-control" name="email" value="{{old('email')}}">
                </div>
              </div>
            </div>
            <div class="row">
               <div class="col-md-12">
                  <label>Seleccione Usuario</label>
                  <select name="rol_id" class="form-control select2" style="width: 100%;">
            @foreach($roles as $rol)
              <option value="{{$rol->id}}">{{$rol->nombre}}</option>
            @endforeach
    
               </select>
                </div>

             </div> 
              <br>
               <div class="col-md-6">
                <div class="form-group {{ $errors->has('password')? 'error':'' }}" >
                  <label for="projectinput3">Contraseña</label>
                  <input type="text" id="projectinput3" class="form-control" name="password" >
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group {{ $errors->has('password')? 'error':'' }}">
                  <label for="projectinput3">Contraseña</label>
                  <input type="text" id="projectinput3" class="form-control" name="password_confirmation">
                </div>
              </div>
            </div>
         
          <div class="form-actions">
             <div class="col-md-2"></div>
            <button type="button" class="btn btn-raised btn-raised btn-danger mr-1">
              <i class="ft-x"></i> Cancelar
            </button>
            <button type="submit" class="btn btn-raised btn-raised btn-success">
              <i class="fa fa-check-square-o"></i> Guardar
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

@endsection

resources/views/User/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
   <div class="col-md-2"></div>
        
  <div class="col-md-12 offset-2">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title" id="basic-layout-form">Editar Usuario</h4>
      </div>
      <div class="card-content">
        <div class="px-3">
          <form class="form" method="POST" action="{{route('user.update',['id'=>$user->id])}}">
            @csrf
            @method('PUT')
            <div class="form-body">
              <h4 class="form-section"><i class="ft-user"></i>Información Personal</h4>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label for="projectinput1">Nombre</label>
                    <input type="text" id="projectinput1" class="form-control" name="nombre" value="{{$user->nombre}}">
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label for="projectinput3">E-mail</label>
                    <input type="text" id="projectinput3" class="form-control" name="email" value="{{$user->email}}">
                  </div>
                </div>
            </div>

            <div class="form-actions">
              <a href="{{route('user.index')}}" class="btn btn-raised btn-raised btn-warning mr-1">
                 Volver
              </a>
              <button type="submit" class="btn btn-raised btn-raised btn-primary">
                <i class="fa fa-check-square-o"></i> Guardar
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/User/index.blade.php
@extends('layouts.app')

@section('content') 
 <div class="col-md-1"></div> 
<div class="col-md-8 offset-2">
<div class="row">
  <section id="ordering">
  <div class="row">
    
      @include('partials.flash')
    
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">Usuarios Registrados</h4>
          <p class="card-text">todos los usuarios.</p>
        </div>
        <div class="card-content">
          <div class="card-body card-dashboard table-responsive">
            <table class="table table-striped table-bordered default-ordering dataTable">
              <thead>
                <tr>
                  <th class="text-center">Nombre</th>
                  <th class="text-center">E-mail</th>
                  <th class="text-center">Accion</th>
                </tr>
              </thead>
              <tbody>
              @foreach($users as $u)
               <tr>
                  <td class="text-center">{{$u->nombre}}</td>
                  <td class="text-center">{{$u->email}}</td>
                  <td class="text-center">
                    <!-- <a href="{{route('user.show',['id' => $u->id])}}" class="btn btn-raised btn-success btn-min-width mr-1 mb-1"><i class="fa fa-eye" title="Ver"></i></a> -->
                    <a href="{{route('user.edit',['id' => $u->id])}}" class="btn btn-raised btn-primary btn-min-width mr-1 mb-1"><i class="fa fa-edit" title="Ver"></i></a>
                  </td>
               </tr>
              @endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>
   
  </div>

</section>
</div>
</div>
<!--/ Default ordering table -->

@endsection

resources/views/apertura/index.blade.php
@extends('layouts.app')

@section('content')

<div class="col-md-8 offset-2">
  <div class="card">
    <div class="card-header">
      <h4 class="card-title" id="basic-layout-form">Platos a Servir
      <p class="mb-0">Registrar usuario nuevo</p>
    </div>
    <div class="card-content">
      <div class="px-3">
        <form class="form" action="" method="POST">
          @csrf
          <div class="form-body">
            <h4 class="form-section"><i class="ft-user"></i>Información Personal</h4>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label for="projectinput1">Nombre</label>
                  <input type="text" id="projectinput1" class="form-control" name="fname">
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label for="projectinput3">E-mail</label>
                  <input type="text" id="projectinput3" class="form-control" name="email">
                </div>
              </div>
               <div class="col-md-6">
                <div class="form-group">
                  <label for="projectinput3">Contraseña</label>
                  <input type="text" id="projectinput3" class="form-control" name="email">
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label for="projectinput3">Contraseña</label>
                  <input type="text" id="projectinput3" class="form-control" name="email">
                </div>
              </div>
            </div>
          </div>
          <div class="form-actions">
            <button type="button" class="btn btn-raised btn-raised btn-warning mr-1">
              <i class="ft-x"></i> Cancelar
            </button>
            <button type="button" class="btn btn-raised btn-raised btn-primary">
              <i class="fa fa-check-square-o"></i> Guardar
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en" class="loading">
  <!-- BEGIN : Head-->
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="Apex admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.">
    <meta name="keywords" content="admin template, Apex admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="PIXINVENT">
    <title>Plantilla</title>
    <link rel="apple-touch-icon" sizes="60x60" href="{{asset('app-assets/img/ico/apple-icon-60.png')}}">
    <link rel="apple-touch-icon" sizes="76x76" href="{{asset('app-assets/img/ico/apple-icon-76.png')}}">
    <link rel="apple-touch-icon" sizes="120x120" href="{{asset('app-assets/img/ico/apple-icon-120.png')}}">
    <link rel="apple-touch-icon" sizes="152x152" href="{{asset('app-assets/img/ico/apple-icon-152.png')}}">
    <link rel="shortcut icon" type="image/x-icon" href="{{asset('app-assets/img/ico/favicon.ico')}}">
    <link rel="shortcut icon" type="image/png" href="{{asset('app-assets/img/ico/favicon-32.png')}}">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900|Montserrat:300,400,500,600,700,800,900" rel="stylesheet">
    <!-- BEGIN VENDOR CSS-->
    <!-- font icons-->
    <link rel="stylesheet" type="text/css" href='{{asset("app-assets/fonts/feather/style.min.css")}}'>
    <link rel="stylesheet" type="text/css" href='{{asset("app-assets/fonts/simple-line-icons/style.css")}}'>
    <link rel="stylesheet" type="text/css" href='{{asset("app-assets/fonts/font-awesome/css/font-awesome.min.css")}}'>
    <link rel="stylesheet" type="text/css" href='{{asset("app-assets/vendors/css/perfect-scrollbar.min.css")}}'>
    <link rel="stylesheet" type="text/css" href='{{asset("app-assets/vendors/css/prism.min.css")}}'>
    <link rel="stylesheet" type="text/css" href='{{asset("app-assets/vendors/css/chartist.min.css")}}'>
    <link rel="stylesheet" type="text/css" href="{{asset('app-assets/vendors/css/tables/datatable/datatables.min.css')}}">
    <!-- END VENDOR CSS-->
    <!-- BEGIN APEX CSS-->
    <link rel="stylesheet" type="text/css" href="{{asset('app-assets/css/app.css')}}">
    <!-- END APEX CSS-->
    <!-- BEGIN Page Level CSS-->
    <!-- END Page Level CSS-->
  </head>
  <!-- END : Head-->

  <!-- BEGIN : Body-->
  <body data-col="2-columns" class=" 2-columns  layout-dark">
    <!-- ////////////////////////////////////////////////////////////////////////////-->
     @include('layouts.menu')


     @include('layouts.navbar')


    <div class="main-panel"> <!-- inicio del dashboard -->
        <!-- BEGIN : Main Content-->
     <!-- CONTENIDO -->
       <div class="main-content">
          <div class="content-wrapper">
            <div class="row">
              @yield('content')
            </div>
          </div>
      </div>

        <!-- END : End Main Content-->

       @include('layouts.footer')

      </div>
    <!-- </div> -->
    <!-- ////////////////////////////////////////////////////////////////////////////-->


    @include('layouts.script')

    <!-- Custom SCRIPT por Pagina -->
    @yield('script')
    <script type="text/javascript">
      $(".dataTable").DataTable({
          responsive: true,
          language: {
            url:'{{asset("app-assets/vendors/js/datatable/spanish.json")}}'
          }
        });
    </script>
  </body>
  <!-- END : Body-->
</html>

resources/views/layouts/footer.blade.php
 <!-- BEGIN : Footer-->
        <footer class="footer footer-static footer-light">
          <p class="clearfix text-muted text-sm-center px-2"><span>Copyright  &copy; 2019 <a href="https://themeforest.net/user/pixinvent/portfolio?ref=pixinvent" id="pixinventLink" target="_blank" class="text-bold-800 primary darken-2">PIXINVENT </a>, All rights reserved. </span></p>
        </footer>
        <!-- End : Footer-->

resources/views/layouts/menu.blade.php
 <div class="wrapper">
      <!-- main menu-->
      <!--.main-menu(class="#{menuColor} #{menuOpenType}", class=(menuShadow == true ? 'menu-shadow' : ''))-->
      <div data-active-color="white" data-background-color="black" data-image="app-assets/img/sidebar-bg/01.jpg" class="app-sidebar">
        <!-- main menu header-->
        <!-- Sidebar Header starts-->
        <div class="sidebar-header">
          <div class="logo clearfix"><a href="{{route('dashboard')}}" class="logo-text float-left">
             <!--  <div class="logo-img"><img src="app-assets/img/logo.png"/></div> --><span class="text align-middle">COMEDOR</span></a><a id="sidebarToggle" href="javascript:;" class="nav-toggle d-none d-sm-none d-md-none d-lg-block"><!-- <i data-toggle="expanded" class="toggle-icon ft-toggle-right"></i></a><a id="sidebarClose" href="javascript:;" class="nav-close d-block d-md-block d-lg-none d-xl-none"><i class="ft-x"></i> --></a></div>
        </div>
        <!-- Sidebar Header Ends-->
        <!-- / main menu header-->
        <!-- main menu content-->
        <div class="sidebar-content">
          <div class="nav-container">
           
            <ul id="main-menu-navigation" data-menu="menu-navigation" data-scroll-to-active="true" class="navigation navigation-main">
             @if(Auth::user()->rol_id == "1")
               <li><a href="#"><i class="fa fa-cutlery" aria-hidden="true"></i><span>Comedor</span></a>
              </li>
              @else
              <li class="has-sub nav-item"><a href="#"><i class="icon-user-follow"></i><span data-i18n="" class="menu-title">Usuarios</span></a>
                <ul class="menu-content">
                  <li><a href="{{route('user.index')}}" class="menu-item">Ver Usuarios</a>
                  </li>
                  <li><a href="{{route('user.create')}}" class="menu-item">Crear Usuario</a>
                  </li>
                </ul>
              </li>
         @endif
              <!-- <li class=" nav-item"><a href="color-palette.html"><i class="ft-droplet"></i><span data-i18n="" class="menu-title">Menu</span></a>
              </li>
              <li class=" nav-item"><a href="inbox.html"><i class="ft-mail"></i><span data-i18n="" class="menu-title">Inbox</span></a>
              </li>
              </li>
              <li class="has-sub nav-item"><a href="#"><i class="ft-aperture"></i><span data-i18n="" class="menu-title">UI Kit</span></a>
                <ul class="menu-content">
                  <li><a href="grids.html" class="menu-item">Grid</a>
                  </li>
                  </li>
                  <li class="has-sub"><a href="#" class="menu-item">Icons</a>
                    <ul class="menu-content">
                      <li><a href="feather.html" class="menu-item">Feather Icon</a>
                      </li>
                      <li><a href="font-awesome.html" class="menu-item">Font Awesome Icon</a>
                      </li>
                      <li><a href="simple-line.html" class="menu-item">Simple Line Icon</a>
                      </li>
                    </ul>
                  </li>
                </ul>
              </li>
              <li class="has-sub nav-item"><a href="#"><i class="ft-box"></i><span data-i18n="" class="menu-title">Components</span></a>
                <ul class="menu-content">
                  <li class="has-sub"><a href="#" class="menu-item">Bootstrap</a>
                    <ul class="menu-content">
                      <li><a href="components-lists.html" class="menu-item">List</a>
                      </li>
                      <li><a href="components-buttons.html" class="menu-item">Buttons</a>
                      </li>
                      <li><a href="components-alerts.html" class="menu-item">Alerts</a>
                      </li>
                      <li><a href="components-badges.html" class="menu-item">Badges</a>
                      </li>
                      <li><a href="components-dropdowns.html" class="menu-item">Dropdowns</a>
                      </li>
                      <li><a href="components-media-objects.html" class="menu-item">Media Objects</a>
                      </li>
                      <li><a href="components-pagination.html" class="menu-item">Pagination</a>
                      </li>
                      <li><a href="components-progress.html" class="menu-item">Progress Bars</a>
                      </li>
                      <li><a href="components-modals.html" class="menu-item">Modals</a>
                      </li>
                      <li><a href="components-collapse.html" class="menu-item">Collapse</a>
                      </li>
                      <li><a href="components-accordion.html" class="menu-item">Accordion</a>
                      </li>
                      <li><a href="components-carousel.html" class="menu-item">Carousel</a>
                      </li>
                      <li><a href="components-datepicker.html" class="menu-item">Datepicker</a>
                      </li>
                      <li><a href="components-popover.html" class="menu-item">Popover</a>
                      </li>
                      <li><a href="components-tabs.html" class="menu-item">Tabs</a>
                      </li>
                      <li><a href="components-tooltip.html" class="menu-item">Tooltip</a>
                      </li>
                      <li><a href="components-spinner.html" class="menu-item">Spinner</a>
                      </li>
                      <li><a href="components-toast.html" class="menu-item">Toast</a>
                      </li>
                      <li><a href="components-radio-checkboxes.html" class="menu-item">Radio &amp; Checkboxes</a>
                      </li>
                    </ul>
                  </li>
                </ul>
              </li>
              <li class=" nav-item"><a href="https://pixinvent.com/apex-angular-4-bootstrap-admin-template/documentation"><i class="ft-book"></i><span data-i18n="" class="menu-title">Documentation</span></a>
              </li>
              <li class=" nav-item"><a href="https://pixinvent.ticksy.com/"><i class="ft-life-buoy"></i><span data-i18n="" class="menu-title">Support</span></a>
              </li>
            </ul> -->
          </div>
        </div>
        <!-- main menu content-->
        <div class="sidebar-background"></div>
        <!-- main menu footer-->
        <!-- include includes/menu-footer-->
        <!-- main menu footer-->
      </div>
      <!-- / main menu-->

resources/views/layouts/script.blade.php
<!-- BEGIN VENDOR JS-->
    <script src="{{asset('app-assets/vendors/js/core/jquery-3.2.1.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('app-assets/vendors/js/core/popper.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('app-assets/vendors/js/core/bootstrap.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('app-assets/vendors/js/perfect-scrollbar.jquery.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('app-assets/vendors/js/prism.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('app-assets/vendors/js/jquery.matchHeight-min.js')}}" type="text/javascript"></script>
    <script src="{{asset('app-assets/vendors/js/screenfull.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('app-assets/vendors/js/pace/pace.min.js')}}" type="text/javascript"></script>
    <!-- BEGIN VENDOR JS-->
    <!-- BEGIN PAGE VENDOR JS-->
    <script src="{{asset('app-assets/vendors/js/chartist.min.js')}}" type="text/javascript"></script>
    <!-- END PAGE VENDOR JS-->
    <!-- BEGIN APEX JS-->
    <script src="{{asset('app-assets/js/app-sidebar.js')}}" type="text/javascript"></script>
    <script src="{{asset('app-assets/js/notification-sidebar.js')}}" type="text/javascript"></script>
    <script src="{{asset('app-assets/js/customizer.js')}}" type="text/javascript"></script>
    <!-- END APEX JS-->
    <!-- BEGIN PAGE LEVEL JS-->
    <script src="{{asset('app-assets/js/dashboard2.js')}}" type="text/javascript"></script>
    <script src="{{asset('app-assets/vendors/js/datatable/datatables.min.js')}}" type="text/javascript"></script>
    <!-- END PAGE LEVEL JS-->

resources/views/partials/flash.blade.php
@if(Session::has('flash_message'))
	<div class="row">
	  <div class="col-md-10 offset-1">
	    <div class="alert {{ Session::get('flash_class') }} {{ Session::has('flash_important') ? 'alert-important':'' }}">
	      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
	      <strong class="text-center">{{Session::get('flash_message')}}</strong>
	  	</div>
	  </div>
	</div>
@endif